export const ActionTypes = {
  GET_META_MASK_ACCOUNT_LOADING: "GET_META_MASK_ACCOUNT_LOADING",
  GET_META_MASK_ACCOUNT_SUCCESS: "GET_META_MASK_ACCOUNT_SUCCESS",
  GET_META_MASK_ACCOUNT_FAIL: "GET_META_MASK_ACCOUNT_FAIL",
};
